config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :conversations do
  	resources :messages
  end

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  resources :friendships

  root "posts#index"

  get 'rooms/show'
  get '/chat' => 'rooms#show'
  mount ActionCable.server => '/cable'

  get '/marketplace' => 'marketplace#index'
  get '/categories' => 'categories#index'
  get '/friendships' => 'friendships#index'

  get '/cart', to: 'order_items#index'
  resources :order_items, path: 'cart/items'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  # This is the model for an order item. 

  # Builds the model for an order item and states the relationships from an order item to different entities. 
  belongs_to :order
  belongs_to :product
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  # The controller for the order items, this contains the actions to add an item to the cart as well as remove 
  # an item from the cart. 

  before_action :authenticate_user!

  def index
    @items = current_cart.order.items
  end

  def create
    current_cart.add_item(
      product_id: params[:product_id], 
      quantity: params[:quantity]
    )
    flash[:notice] = "Your item has been added to cart."
    redirect_to cart_path
  end

  def destroy
    current_cart.remove_item(id: params[:id])
    flash[:notice] = "Your item has been removed from the cart."
    redirect_to cart_path
  end
end

app/views/order_items/index.html.erb
<%# The view for the order items index page. %>

<%# This appends to the title of the page. %>
<% content_for :title, " - Checkout" %>

<%# This contains the contents of the shopping cart before you checkout. %>
<div class="cart-container">
  <div class="columns is-centered">
    <%# Displays the items which have been added to the cart. %>
    <div class="column is-two-thirds">
      <div class="cart-products">
        <h1>Shopping Cart</h1>
        <div class="columns is-mobile cart-table">
          <div class="column is-half table-heading">
            <h2>Product Details</h2>
          </div>
          <div class="column table-heading center">
            <h2>Remove</h2>
          </div>
          <div class="column table-heading center">
            <h2>Price</h2>
          </div>
          <div class="column table-heading center">
            <h2>Total</h2>
          </div>
        </div>
        <%# Displays the contents of each item which has been added to the basket. %>
        <% @items.each do |item| %>
          <div class="columns is-mobile cart-row">
            <div class="column is-half">
              <h2><%= item.product.title %></h2>
              <p><%= item.product.description %></p>
            </div>
            <div class="column center">
              <h2><%= form_for item, method: :delete do |f| %>
                <%= f.submit "Remove", class: "remove-button" %>
              <% end %></h2>
            </div>
            <div class="column center">
              <h2><%= price(item.price) %></h2>
            </div>
            <div class="column center">
              <h2><%= price(current_cart.order_total) %></h2>
            </div>
          </div>
        <% end %>
      </div>
      <h3>
        <%= link_to "Continue Shopping", categories_path, class: "back-link" %>
      </h3>
    </div>
    
    <%# Displays the panel which allows you to confirm the purchase. %>
    <div class="column">
      <div class="total-price-box">
        <h1>Order Summary</h1>
        <hr>
        <div class="columns text-row is-mobile">
          <div class="column is-half">
            <h2 class="left-text">Items <%= current_cart.count_items %></h2>
          </div>
          <div class="column">
            <h2 class="right-text"><%= price(current_cart.order_total) %></h2>
          </div>
        </div>
        <div class="delivery-info">
          <h2>Standard Delivery - Free</h2>
        </div>
        <hr>
        <div class="columns text-row is-mobile">
          <div class="column is-half">
            <h2 class="left-text total">Total Cost</h2>
          </div>
          <div class="column">
            <h2 class="right-text"><%= price(current_cart.order_total) %></h2>
          </div>
        </div>
        <span>
          <%= button_to 'Checkout', checkout_create_path, method: :post, params: {id: current_cart.order_total}, remote: true, class: "checkout-button" %>
        </span>
      </div>
    </div>

  </div>
</div>