config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :conversations do
  	resources :messages
  end

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  resources :friendships

  root "posts#index"

  get 'rooms/show'
  get '/chat' => 'rooms#show'
  mount ActionCable.server => '/cable'

  get '/marketplace' => 'marketplace#index'
  get '/categories' => 'categories#index'
  get '/friendships' => 'friendships#index'

  get '/cart', to: 'order_items#index'
  resources :order_items, path: 'cart/items'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # This is the model for a post. 

	# Builds the model for a post and states the relationships from a post to different entities.  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # States that a post cannot be empty. 
  validates_presence_of :post, allow_blank: false
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # The controller for the posts, this was used to define the methods which were needed for posts e.g. create and edit. 

  # These actions are performed before any of the methods can be performed on a post. The user is authenticated 
  # before they can configure a post however, if a user is not signed in, they can still view the posts. 
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC") # Ordered by DESC so that most recent posts show at the top of 
    # the feed
    @post = Post.new
    @users = User.last(6)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order("created_at DESC")
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        ActionCable.server.broadcast('notification_channel', 'A new post has been added!')
      else
        format.html { redirect_to root_path, notice: 'Post cannot be left blank.' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { redirect_to post_path, notice: 'Post cannot be left blank.' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post)
    end
end

app/views/posts/_edit-form.erb
<%# The view for the edit posts page. 
    This allows you to edit the contents of a post. %>
<%= simple_form_for(@post) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
      <%= f.input :post, label: t("update"), input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" } %>
  </div>
</div>
<%= f.button :submit, value: t("form_update"), class: "post-btn" %>
<% end %>

app/views/posts/_feed.html.erb
<%# The partial for the posts feed. %>

<%# This section checks if a user has signed in and if they have it renders the form to create a new post. %>
<div class="column is-half">
  <% if user_signed_in? %>
    <article class="media">
      
      <%# This displays the form to create a new post %>
      <div class="media-content">
        <div class="content">
        <%= render 'posts/form' %>
        </div>
      </div>
    </article>
  <% end %>

  <h1 class="posts-title">Posts</h1>
  
  <%# This section determines how the posts will look when they are displayed on the feed. %>
  <% @posts.each do | post | %>

    <div class="columns is-mobile is-centered">
      <div class="post-container is-centered">
        <span class="post-date right"><%= post.created_at.strftime("%B %-d %Y, %H:%M") %></span>
        
        <%# Displays the user avatar. %>
        <div class="columns is-vcentered">
          <div class="column is-2 avatar-post">
            <%= avatar_for(post.user, size: 60)  %>
          </div>
          
          <%# Displays the content of the post %>
          <div class="column post-content">
            <strong><%= post.user.try(:name) %></strong><br />
            <small>@<%= post.user.try(:username) %></small>
            <p><%= post.post %></p>
          </div>
        </div>

        <%# Displays the number of comments and likes on posts. %>
        <%= pluralize(post.comments.count, t("comment")) %> | <%= pluralize(post.likes.count, t("like")) %> | 
        <%# Displays a link to show the thread of the post so the user can like and comment. %>
        <%= link_to post_path(post) do %>
          <% t ".show_thread" %>
        <% end %>

        <%# If the user signed in created the post or is an admin user, they are able to delete the post. %>
        <% if user_signed_in? && current_user.id == post.user_id || current_user && current_user.admin %>
          <div class="right">
            <%= link_to post, method: :delete, data: { confirm: t("delete_confirmation") } do %>
              <%= t("delete") %><p><span class="icon"><i class="fa fa-trash" aria-hidden="hidden"></i></span>
            <% end %>
          </div>
        <% end %>
        
        <%# If the user is an admin user, a link to edit each post is displayed. %>
        <% if current_user && current_user.admin %>
          <div class="right">
            <%= link_to edit_post_path(post) do %>
              <%= t("edit") %><span class="icon"><i class="fa fa-pencil"></i></span>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%# The partial for the posts form. %>

<%# Creates a form which the user can use to create a post. %>
<%= form_for @post do |f| %>
  <div class="form">
    <%= f.text_field :post, autocomplete: "off", autofocus: true, required: true %>
    <%= f.label :name, class: "label-name" do %>
      <span class="content-name"><%= t("greeting") + " " + current_user.try(:name).to_s.html_safe + ", " + t("greeting_two") %></span>
    <% end %>
  </div>
<% end %>

app/views/posts/_people-you-may-know.html.erb
<%# The partial for the "people you may know" section. %>

<div class="flex-container">
  <div class="box-1">
    <p class="block rounded-corner-1"><%= t ".title" %></p>
    <%# Displays the users which are signed up to the website %>
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
        <div class="box-2">
          <div class="block flex">
            <div class="items">
              <div class="column-1">
                <h3 style="font-size: 20px;"><%= link_to user.name %></h3>
              </div>
            </div>
            <div class="items right">
              <div class="column-2">
                <%= string_with_link(t('.add_friend'), friendships_path(:friend_id => user), :method => :post) %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    <div class="block flex last-rounded-corner">
      <%= link_to "Show All", friendships_path, class: "items bold-text" %>
    </div>
  </div>
</div>

app/views/posts/_profile.html.erb
<%# The partial for the "profile" section. %>

<div class="flex-container">
  <div class="box-1">
    <p class="block rounded-corner-1"><%= t ".title" %></p>
    <div class="block flex">
      <%# Displays the avatar which is associated with a user. %>
      <%= avatar_for(current_user, size: 80) %>
      <p class="name">
        <%# Displays the users name and username %>
        <strong><%= current_user.name %></strong> |
        <small>@<%= current_user.username %></small> <br>
        <%# Displays "Admin" text if the user is an admin user. %>
        <% if current_user && current_user.admin %>
          <strong class="admin-text">(Admin)</strong>
        <% end %>
      </p>
    </div>
    <div class="box-2">
      <div class="block flex center-text">
        <div class="items">
          <div class="column-1">
            <p><%= t ".posts" %></p>
             <%# Displays the number of posts which the user has associated with their account. %>
            <h3 class="strong-text"><%= current_user.posts.count %></h3>
          </div>
        </div>
        <div class="items">
          <div class="column-2">
            <p><%= t ".following" %></p>
            <%# Displays the number of friends which the user has associated with their account. %>
            <h3 class="strong-text"><%= current_user.friendships.count %></h3>
          </div>
        </div>
      </div>
    </div>
    <div class="box-3">
      <%# Button which links to the messages page where you can create conversations with users %>
      <%= link_to edit_user_registration_path, class: 'links' do %>
        <div class="block flex">
          <p>
            <i class="fas fa-cog icon-edit-profile"></i>
            <%= t('.edit_profile') %>
        </div>
      <% end %>
    </div>
    <div class="box-4">
      <%# Button which links to the messages page where you can create conversations with users %>
      <%= link_to chat_path, class: 'links' do %>
        <div class="block flex">
          <p>
            <i class="fas fa-comment-dots icon-chat"></i>
            <%= t('.messages') %>
          </p>
        </div>
      <% end %>
    </div>
    <div class="box-5">
      <%# Button which links to the marketplace page %>
      <%= link_to categories_path, class: 'links' do %>
        <div class="block flex">
          <p>
            <i class="fas fa-store icon-marketplace"></i>
            <%= t('.marketplace') %>
          </p>
        </div>
      <% end %>
    </div>
    <div class="box-6">
      <%# Button which links to the friendships page %>
      <%= link_to friendships_path, class: 'links' do %>
        <div class="block flex rounded-corner">
          <p>
            <i class="fas fa-users icon-friendships"></i>
            <%= t('.friendships') %> (<%= current_user.friendships.count %>)
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%# The view for the edit posts page. %>

<%# This appends to the title of the page. %>
<% content_for :title, " - Edit Post" %>

<%# Renders the form partial to edit a post  %>
<div class="columns is-centered is-mobile">
  <div class="column is-half">
    <h1><%= t(".edit_post_title") %></h1>

    <%= render 'form', post: @post %>

    <%= link_to t(".show_link"), @post %> |
    <%= link_to t(".back_link"), posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<%# The view for the posts index page. %>

<%# This appends to the title of the page, if a user is signed in. %>
<% if current_user %>
  <% content_for :title, " - " + current_user.name %>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">

    <%# If the user is signed in, render the "profile" section. %>
    <% if user_signed_in? %>
      <div class="column is-4">
        <%= render 'profile' %>
      </div>
    <% end %>

    <%= render 'feed' %>

    <%# If the user is signed in, render the "people you may know" section. %>
    <% if user_signed_in? %>
      <div class="column is-4">
        <%= render 'people-you-may-know' %>
      </div>
    <% end %>

    </div>
  </div>
</section>

app/views/posts/new.html.erb
<%= render 'posts/form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%# The view for the show page for posts. %>

<div class="container-show">
  <%# If the user signed in created the post, display the form to edit the post. %>
  <% if user_signed_in? && current_user.id == @post.user_id %>
    <div class="columns update-form">
      <%= render 'edit-form', post: @post %>
    </div>
  <% end %>

  <%# Displays the comments which have been created on a post. %>
  <div class="comments">
    <div class="box post-panel">
      <article class="media">
        <div class="media-left">
          <figure class="image">
            <%= avatar_for(@post.user) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong><%= @post.user.try(:name) %></strong><br />
            <small>@<%= @post.user.try(:username) %></small>
            <p><%= @post.post %></p>
          </div>

          <div class="right">
            <% not_liked = @post.likes.find { |like| like.try(:user_id) == current_user.try(:id)} %>
            <% if not_liked %>
              <%= link_to post_like_path(@post, not_liked), method: :delete, class: 'unlike-icon' do %>
                <i class="fas fa-thumbs-up"></i><%= t("unlike") %>
              <% end %>
            <% else %>
              <%= link_to post_likes_path(@post), method: :post, class: 'like-icon' do %>
                <i class="far fa-thumbs-up"></i><%= t("like") %>
              <% end %>
            <% end %>
            <span class="likes-breakpoint">|</span>
            <p><%= pluralize(@post.likes.count, t("like")) %></p>
          </div>
        </article>
      </div>
    
      <div class="center">
        <%= link_to t('back'), posts_path %>
      </div>

      <%# If a user is signed in, display the comments form and comments on a post, else display a link to 
          sign-in. %>
      <% if current_user %>
        <%# Displays the form to create a comment. %>
        <div class="box form-panel">
          <%= form_with model: [@post, @comment] do |f| %>
            <%= f.text_field :body, autofocus: true, autocomplete: "off", class: "text-field", placeholder: t('comment_placeholder') %>
            <%= f.submit t("comment_button") %>
          <% end %>
          <div id="comment_section">
          <% @comments.each do |comment| %>
            <div class="box comment-panel">
              <%= render 'comments/comment', comment: comment %>
            </div>
          <% end %>
          </div>
        </div>
      <% else %>
        <p class="center">
          You need to <%= link_to "Sign In", new_user_session_path %> to comment on a post!
        </p>
      <% end %>
    </div>
  </div>
</div>