config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :conversations do
  	resources :messages
  end

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  resources :friendships

  root "posts#index"

  get 'rooms/show'
  get '/chat' => 'rooms#show'
  mount ActionCable.server => '/cable'

  get '/marketplace' => 'marketplace#index'
  get '/categories' => 'categories#index'
  get '/friendships' => 'friendships#index'

  get '/cart', to: 'order_items#index'
  resources :order_items, path: 'cart/items'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  # This is the model for a category. 

  # Builds the model for a category and states the relationships from a category to different entities. 
  has_many :product_categories
  has_many :products, through: :product_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # The controller for the categories, this contains index action which uses an sql query to group the categories. 

  # Checks that a user is signed in before they can access the categories page. 
  before_action :authenticate_user!
  
  def index
    @categories = Category.joins(:products).select('categories.*, count(products.id) as products_count').group('categories.id').order("title")
  end
end

app/views/categories/index.html.erb
<%# The view for the categories index page. %>

<%# This appends to the title of the page. %>
<% content_for :title, " - Marketplace Categories" %>

<h2 class="categories-title">
  <%= t('category') %>
</h2>

<ol>
  <%# Loops through the categories and displays them as an ordered list. %>
  <% @categories.each do |category| %>
  <li class="center">
    <%= link_to category_products_path(category) do %> <%= category.title %>
    (<%= pluralize(category.products_count, "product") %>)
    <hr />
    <% end %>
  </li>
  <% end %>
</ol>