config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :conversations do
  	resources :messages
  end

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  resources :friendships

  root "posts#index"

  get 'rooms/show'
  get '/chat' => 'rooms#show'
  mount ActionCable.server => '/cable'

  get '/marketplace' => 'marketplace#index'
  get '/categories' => 'categories#index'
  get '/friendships' => 'friendships#index'

  get '/cart', to: 'order_items#index'
  resources :order_items, path: 'cart/items'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # This is the model for a product. 

  # Builds the model for a product and states the relationships from a product to different entities. 
  has_many :product_categories
  has_many :categories, through: :product_categories
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # The controller for the products, this contains the index action which finds the products which are in the 
  # selected category. 

  before_action :authenticate_user!
  
  def index
    @category = Category.find(params[:category_id])
    @products = @category.products.order(:title)
  end
end

app/views/products/index.html.erb
<%# The view for the products index page. %>

<%# This appends to the title of the page. %>
<% content_for :title, " - Products " + "(" + @category.title + ")" %>

<div class="container-wrap">
  <h2>
    <%= link_to t("category"), categories_path %> /
    <%= @category.title %> /
    Products
  </h2>
  <div class="products">
    <%# Loops through each of the products and displays the products on the page. %>
    <% @products.each do |product| %>
      <div class="product-card">
        <div class="card-head">
          <%= image_tag "logo.svg", class: "card-logo" %>
          <div class="product-detail">
            <span class="back-text">
              Buy
            </span>
          </div>
        </div>
        <div class="card-body">
          <div class="product-description">
            <span class="product-title">
              <%= product.title %>
            </span>
            <span class="product-caption">
              <%= @category.title %>
            </span>
            <span class="product-description">
              <%= product.description %>
            </span>
          </div>
          <div class="product-properties">
            <%= form_tag order_items_path, class: "product-price" do %>
              <%= hidden_field_tag :product_id, product.id %>
              <%# Adds a button to add the item to cart. %>
              <%= button_tag(type: "submit", class: "add-to-basket-button") do %>
                <%= price(product.price) %>
                <i class="fas fa-shopping-cart"></i>
              <% end %>
            <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>